"""
Query parametric model inputs by unit instance id or obsBrandGoodId.

Usage (exactly one required; do not mix):
    python skills/shared/scripts/query_param_list.py --id INSTANCE_ID [INSTANCE_ID ...]
    python skills/shared/scripts/query_param_list.py --bgid BGID [BGID ...]

Use ``--id`` with ``abd.json`` ``units[].id`` for per-instance current parameters;
use ``--bgid`` for product template obsBrandGoodId.

Reads workspace/tmp/input/param_current.json first if it exists,
then calls get_products_parameters API as fallback.

When param_current.json doesn't exist and abd.json contains
``obsCollectBrandGoodId``, the file is generated from that id. If obsCollectBrandGoodId
is not present but ``designId`` or combination ``id`` exists, the file is generated by
fetching design parameters from the param-platform API.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Sequence
from pathlib import Path
from typing import Any, Literal

QueryIdKind = Literal["instance", "obs"]

REPO_ROOT = Path(__file__).resolve().parents[4]
UTILS_DIR = REPO_ROOT / "data-tools" / "utils"
SCRIPTS_DIR = Path(__file__).resolve().parent
if str(UTILS_DIR) not in sys.path:
    sys.path.insert(0, str(UTILS_DIR))
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

FETCH_MODEL_LIBRARY_DIR = UTILS_DIR / "fetch_model_library"
if str(FETCH_MODEL_LIBRARY_DIR) not in sys.path:
    sys.path.insert(0, str(FETCH_MODEL_LIBRARY_DIR))

import get_composite_units_param
from api import get_products_parameters
from param_value_normalize import format_param_value_for_export

WORKSPACE_ROOT = Path(__file__).resolve().parents[3]

ABD_FILE = WORKSPACE_ROOT / "tmp" / "input" / "abd.json"
CURRENT_VALUE_FILE = WORKSPACE_ROOT / "tmp" / "input" / "param_current.json"

_PARAMS_MAP_CACHE: dict[str, str] | None = None


def _load_params_map() -> dict[str, str]:
    global _PARAMS_MAP_CACHE
    if _PARAMS_MAP_CACHE is not None:
        return _PARAMS_MAP_CACHE
    map_path = FETCH_MODEL_LIBRARY_DIR / "params_map.json"
    if map_path.exists():
        with map_path.open(encoding="utf-8") as f:
            _PARAMS_MAP_CACHE = json.load(f)
    else:
        _PARAMS_MAP_CACHE = {}
    return _PARAMS_MAP_CACHE


def normalize_model_param_names(inputs: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Rename paramName entries using params_map.json (e.g. CZ -> materialBrandGoodId)."""
    params_map = _load_params_map()
    if not params_map or not inputs:
        return inputs
    for param in inputs:
        if isinstance(param, dict):
            name = param.get("paramName")
            if name in params_map:
                param["paramName"] = params_map[name]
    return inputs


ParamInputs = list[dict[str, Any]]
ParamQueryEntry = dict[str, Any]
ParamMap = dict[str, ParamQueryEntry]


class AbdUnitIndex:
    """Maps abd.json unit instance id and obsBrandGoodId."""

    def __init__(self) -> None:
        self.unit_id_to_obs: dict[str, str] = {}
        self.obs_to_unit_id: dict[str, str] = {}

    @classmethod
    def from_abd(cls, abd_data: dict[str, Any] | None) -> AbdUnitIndex | None:
        if abd_data is None:
            return None
        units = abd_data.get("units")
        if not isinstance(units, list):
            return None
        index = cls()
        for unit in units:
            if not isinstance(unit, dict):
                continue
            obs_id = unit.get("obsBrandGoodId")
            unit_id = unit.get("id")
            if not isinstance(obs_id, str) or not obs_id.strip():
                continue
            obs_id = obs_id.strip()
            if isinstance(unit_id, str) and unit_id.strip():
                unit_id = unit_id.strip()
                index.unit_id_to_obs[unit_id] = obs_id
                index.obs_to_unit_id[obs_id] = unit_id
            else:
                index.obs_to_unit_id.setdefault(obs_id, "")
        return index if index.unit_id_to_obs or index.obs_to_unit_id else None


def get_param_inputs(entry: ParamQueryEntry | ParamInputs) -> ParamInputs:
    """Return the inputs list from a :func:`query_param_list` result entry."""
    if isinstance(entry, dict) and isinstance(entry.get("inputs"), list):
        return entry["inputs"]
    if isinstance(entry, list):
        return entry
    return []


def _build_query_result_entry(
    *,
    obs_brand_good_id: str | None,
    unit_id: str | None,
    inputs: ParamInputs,
) -> ParamQueryEntry:
    """Build CLI/API result object; key order: obsBrandGoodId, id, inputs."""
    entry: ParamQueryEntry = {}
    if obs_brand_good_id:
        entry["obsBrandGoodId"] = obs_brand_good_id
    if unit_id:
        entry["id"] = unit_id
    entry["inputs"] = inputs
    return entry


def _resolve_obs_brand_good_id(
    query_key: str,
    abd_index: AbdUnitIndex | None,
    *,
    kind: QueryIdKind,
) -> str:
    """Resolve API/cache lookup key (always obsBrandGoodId)."""
    if kind == "obs":
        return query_key
    if abd_index is not None and query_key in abd_index.unit_id_to_obs:
        return abd_index.unit_id_to_obs[query_key]
    return query_key


def _build_query_items(
    *,
    instance_ids: Sequence[str] | None = None,
    obs_brand_good_ids: Sequence[str] | None = None,
) -> list[tuple[str, QueryIdKind]]:
    """Build query list from exactly one of instance_ids or obs_brand_good_ids."""
    inst = _normalize_ids(instance_ids)
    obs = _normalize_ids(obs_brand_good_ids)
    if inst and obs:
        raise ValueError(
            "Cannot mix instance_ids and obs_brand_good_ids; use --id or --bgid"
        )
    if not inst and not obs:
        raise ValueError(
            "Must provide either instance_ids or obs_brand_good_ids; "
            "use --id or --bgid"
        )
    if inst:
        return [(value, "instance") for value in inst]
    return [(value, "obs") for value in obs]


def _result_ids_for_query(
    query_key: str,
    model: dict[str, Any] | None,
    abd_index: AbdUnitIndex | None,
    kind: QueryIdKind,
) -> tuple[str | None, str | None]:
    obs_id: str | None = None
    unit_id: str | None = None
    if model:
        if isinstance(model.get("obsBrandGoodId"), str):
            obs_id = model["obsBrandGoodId"]
        if isinstance(model.get("id"), str) and model["id"]:
            unit_id = model["id"]

    if kind == "instance":
        unit_id = unit_id or query_key
        if abd_index is not None and query_key in abd_index.unit_id_to_obs:
            obs_id = obs_id or abd_index.unit_id_to_obs[query_key]
    else:
        obs_id = obs_id or query_key
        if abd_index is not None:
            mapped = abd_index.obs_to_unit_id.get(query_key)
            if mapped:
                unit_id = unit_id or mapped

    return obs_id, unit_id


def _load_abd_json() -> dict[str, Any] | None:
    if not ABD_FILE.exists():
        return None
    try:
        with ABD_FILE.open(encoding="utf-8") as f:
            data = json.load(f)
        return data if isinstance(data, dict) else None
    except (json.JSONDecodeError, OSError):
        return None


def query_param_list(
    *,
    instance_ids: Sequence[str] | None = None,
    obs_brand_good_ids: Sequence[str] | None = None,
    param_names: Sequence[str] | None = None,
) -> ParamMap:
    """
    Return parameter entries keyed by the requested id (instance id or obsBrandGoodId).

    Each value is ``{"obsBrandGoodId": ..., "id": ...?, "inputs": [...]}``.
    ``id`` is included when known from the cache or ``abd.json``.

    Requires exactly one of ``instance_ids`` (``--id``) or ``obs_brand_good_ids``
    (``--bgid``).

    Reads ``workspace/tmp/input/param_current.json`` first if it exists.
    Missing models fall back to ``get_products_parameters`` API.
    """
    query_items = _build_query_items(
        instance_ids=instance_ids,
        obs_brand_good_ids=obs_brand_good_ids,
    )

    name_filter = _normalize_param_names(param_names)
    abd_index = AbdUnitIndex.from_abd(_load_abd_json())

    # --- current-value shortcut ---
    current_store: ParamListStore | None = None
    if not CURRENT_VALUE_FILE.exists():
        get_composite_units_param.generate_current_value_file()
    if CURRENT_VALUE_FILE.exists():
        current_store = ParamListStore(CURRENT_VALUE_FILE)

    remaining_obs: list[str] = []
    seen_obs: set[str] = set()
    for query_key, kind in query_items:
        if current_store is not None and current_store.has_query_key(
            query_key, abd_index, kind=kind
        ):
            continue
        obs_id = _resolve_obs_brand_good_id(query_key, abd_index, kind=kind)
        if obs_id not in seen_obs:
            seen_obs.add(obs_id)
            remaining_obs.append(obs_id)

    api_results_by_obs: dict[str, dict[str, Any]] = {}
    if remaining_obs:
        try:
            api_results = get_products_parameters(remaining_obs)
            for result in api_results:
                bgid = result.get("obsBrandGoodId")
                if isinstance(bgid, str):
                    api_results_by_obs[bgid] = result
        except Exception as e:
            print(f"warning: API fallback failed: {e}", file=sys.stderr)

    result: ParamMap = {}
    for query_key, kind in query_items:
        model: dict[str, Any] | None = None
        if current_store is not None:
            model = current_store.find_model_for_query_key(query_key, abd_index, kind=kind)
        if model is None:
            obs_id = _resolve_obs_brand_good_id(query_key, abd_index, kind=kind)
            model = api_results_by_obs.get(obs_id)

        raw_inputs = model.get("inputs", []) if model else []
        if not isinstance(raw_inputs, list):
            raw_inputs = []
        cleaned_inputs = [
            _clean_param_output(param)
            for param in _filter_inputs(raw_inputs, name_filter)
        ]

        obs_id, unit_id = _result_ids_for_query(query_key, model, abd_index, kind)

        result[query_key] = _build_query_result_entry(
            obs_brand_good_id=obs_id,
            unit_id=unit_id,
            inputs=cleaned_inputs,
        )
    return result


def _normalize_ids(obs_brand_good_ids: str | Sequence[str] | None) -> list[str]:
    if obs_brand_good_ids is None:
        return []
    if isinstance(obs_brand_good_ids, str):
        raw = [obs_brand_good_ids]
    else:
        raw = list(obs_brand_good_ids)
    seen: set[str] = set()
    ordered: list[str] = []
    for item in raw:
        obs_id = str(item).strip()
        if not obs_id or obs_id in seen:
            continue
        seen.add(obs_id)
        ordered.append(obs_id)
    return ordered


def _normalize_param_names(param_names: Sequence[str] | None) -> frozenset[str] | None:
    if param_names is None:
        return None
    names = frozenset(str(name).strip() for name in param_names if str(name).strip())
    return names or None


def _filter_inputs(inputs: ParamInputs, param_names: frozenset[str] | None) -> ParamInputs:
    if param_names is None:
        return inputs
    return [
        param
        for param in inputs
        if isinstance(param, dict) and str(param.get("paramName", "")) in param_names
    ]


def _clean_param_output(param: dict[str, Any]) -> dict[str, Any]:
    """Clean parameter output by conditionally including min/max and keeping displayName."""
    result = {}
    value_type = str(param.get("valueType") or "")

    for key, value in param.items():
        # Keep displayName in the output
        # Only include min/max if they are not empty strings
        if key in ("min", "max") and value == "":
            continue

        if key == "value" and value_type in ("material", "style"):
            if isinstance(value, str):
                result[key] = value
            else:
                result[key] = format_param_value_for_export(value, value_type)
        else:
            result[key] = value

    return result


class ParamListStore:
    def __init__(self, path: Path) -> None:
        self.path = path
        self._data = self._load()

    def _load(self) -> dict[str, Any]:
        if not self.path.exists():
            return {"param_list": []}
        with self.path.open(encoding="utf-8") as f:
            data = json.load(f)
        if not isinstance(data, dict):
            raise ValueError(f"{self.path} must contain a JSON object")
        if not isinstance(data.get("param_list"), list):
            data["param_list"] = []
        return data

    def save(self) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        with self.path.open("w", encoding="utf-8", newline="\n") as f:
            json.dump(self._data, f, ensure_ascii=False, indent=2)
            f.write("\n")

    def has(self, obs_brand_good_id: str) -> bool:
        return self.find_model_by_obs(obs_brand_good_id) is not None

    def has_query_key(
        self,
        query_key: str,
        abd_index: AbdUnitIndex | None,
        *,
        kind: QueryIdKind,
    ) -> bool:
        return self.find_model_for_query_key(query_key, abd_index, kind=kind) is not None

    def get_inputs(self, obs_brand_good_id: str) -> ParamInputs:
        model = self.find_model_by_obs(obs_brand_good_id)
        if model is None:
            return []
        inputs = model.get("inputs", [])
        return inputs if isinstance(inputs, list) else []

    def find_model_by_obs(self, obs_brand_good_id: str) -> dict[str, Any] | None:
        target = str(obs_brand_good_id)
        for category in self._data.get("param_list", []):
            if not isinstance(category, dict):
                continue
            for model in category.get("models", []):
                if isinstance(model, dict) and str(model.get("obsBrandGoodId", "")) == target:
                    return model
        return None

    def find_model_by_unit_id(self, unit_id: str) -> dict[str, Any] | None:
        target = str(unit_id)
        for category in self._data.get("param_list", []):
            if not isinstance(category, dict):
                continue
            for model in category.get("models", []):
                if isinstance(model, dict) and str(model.get("id", "")) == target:
                    return model
        return None

    def find_model_for_query_key(
        self,
        query_key: str,
        abd_index: AbdUnitIndex | None,
        *,
        kind: QueryIdKind,
    ) -> dict[str, Any] | None:
        """Resolve model by instance id or obsBrandGoodId."""
        if kind == "instance":
            model = self.find_model_by_unit_id(query_key)
            if model is not None:
                return model
            if abd_index is not None and query_key in abd_index.unit_id_to_obs:
                return self.find_model_by_obs(abd_index.unit_id_to_obs[query_key])
            return None
        return self.find_model_by_obs(query_key)

    def find_model(self, obs_brand_good_id: str) -> dict[str, Any] | None:
        return self.find_model_by_obs(obs_brand_good_id)


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Query parametric model inputs by unit instance id or obsBrandGoodId. "
            "Requires exactly one of --id or --bgid."
        ),
    )
    query_group = parser.add_mutually_exclusive_group(required=False)
    query_group.add_argument(
        "--id",
        dest="instance_ids",
        nargs="+",
        metavar="INSTANCE_ID",
        help="Unit instance id from abd.json units[].id",
    )
    query_group.add_argument(
        "--bgid",
        dest="obs_brand_good_ids",
        nargs="+",
        metavar="BGID",
        help="Product template obsBrandGoodId (bgId)",
    )
    parser.add_argument(
        "--filter",
        dest="param_names",
        default=None,
        help="Comma-separated paramName list",
    )
    args = parser.parse_args()

    param_names = None
    if args.param_names:
        param_names = [part.strip() for part in args.param_names.split(",") if part.strip()]

    try:
        if args.instance_ids is not None:
            result = query_param_list(
                instance_ids=args.instance_ids,
                param_names=param_names,
            )
        elif args.obs_brand_good_ids is not None:
            result = query_param_list(
                obs_brand_good_ids=args.obs_brand_good_ids,
                param_names=param_names,
            )
        else:
            print(
                "Error: --id or --bgid is required",
                file=sys.stderr,
            )
            return 1
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
